version: '3'

services:
  maria:
    container_name: maria
    hostname: maria
    restart: always
    image: mariadb:11.3.2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    networks:
      - my-beauty-network

  postgres:
    container_name: postgres
    hostname: postgres
    restart: always
    image: postgres:15.6
    environment:
      - ${POSTGRES_PORT}=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - my-beauty-network

  mongo:
    container_name: mongo
    hostname: mongo
    restart: always
    image: mongo:7.0.6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - my-beauty-network

networks:
  "${add-your-custom-network}":
    external: true
